version: "3.8"

services:
    nginx:
        ports:
            - 443:443
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        container_name: nginx
        restart: always
        env_file:
            - .env
        volumes:
           - wordpress:/var/www/html
        networks:
            - inception-network
        depends_on:
            - wordpress
    
    mariadb:
        ports:
            - 3306:3306
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        container_name: mariadb
        restart: always
        volumes:
            - mariadb-data:/var/lib/mysql
        env_file:
            - .env
        networks:
            - inception-network
        
    wordpress:
        ports:
            - 9000:9000
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        container_name: wordpress
        restart: always
        volumes:
            - wordpress:/var/www/html
        env_file:
            - .env
        depends_on:
            - mariadb
        networks:
            - inception-network
        
volumes:
    mariadb-data:
        name: mariadb-data
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/zmoussam/data/database
    wordpress:
        name: wordpress
        driver: local
        driver_opts: 
            type: none
            o: bind 
            device: /Users/zmoussam/data/wordpress
networks:
    inception-network:
        name: inception-network
        driver: bridge