version: '3'

services:
    nginx:
        ports:
            - 443:443
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        container_name: nginx
        restart: always
    mariadb:
  
volumes:
    db-wordpress:
    wordpress: